# Generated by Django 4.2.26 on 2025-11-23 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=150, verbose_name='Destino')),
                ('data_partida', models.DateField(blank=True, null=True, verbose_name='Data de partida')),
                ('data_retorno', models.DateField(blank=True, null=True, verbose_name='Data de retorno')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição/Observações')),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='planejada', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'ordering': ['-criado_em'],
            },
        ),
    ]
