# Generated by Django 4.2.26 on 2025-11-23 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viagem',
            options={},
        ),
        migrations.RemoveField(
            model_name='viagem',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='viagem',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='viagem',
            name='data_partida',
        ),
        migrations.RemoveField(
            model_name='viagem',
            name='data_retorno',
        ),
        migrations.RemoveField(
            model_name='viagem',
            name='status',
        ),
        migrations.AddField(
            model_name='viagem',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='destino',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
